services:
  bedrock:
    container_name: mc_bedrock
    image: itzg/minecraft-bedrock-server
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      EULA: "TRUE"
      SERVER_NAME: "4S Minecraft"
      GAMEMODE: "survival"
      FORCE_GAMEMODE: true
      DIFFICULTY: "normal"
      ALLOW_CHEATS: false
      MAX_PLAYERS: 50
      ONLINE_MODE: true
      ALLOW_LIST: false
      PLAYER_IDLE_TIMEOUT: 0
      MAX_THREADS: 0
      DEFAULT_PLAYER_PERMISSION: "member" # 参加者の権限
      OPS: "2535457866812073" #OP権限を持つプレイヤーのXUID.
      OP_PERMISSION_LEVEL: 4
      LEVEL_NAME: "world"
      VERSION: "LATEST"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    restart: unless-stopped
  backups:
    container_name: mc_bedrock_backups
    image: kaiede/minecraft-bedrock-backup
    depends_on:
      - bedrock
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./config/backup:/config
      - ./backups:/backups
        ./data:/data
